In [6]:
import numpy as np

# 创建一个36个元素的数组
np_array = np.arange(36)
print(np_array)
# 数组重组
np_array_shape = np_array.reshape(4,3,3)
print(np_array_shape)
# 索引对应的数据
print(np_array[5])
print(np_array_shape[0,1,2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
5
5


In [15]:
# 数组切片
# 一维切片
np_array[5:]
np_array[:5]

# 二维切片
np_array_2 = np_array.reshape(6,6)
print(np_array_2)

print(np_array_2[:,1])
print(np_array_2[1,:])



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 1  7 13 19 25 31]
[ 6  7  8  9 10 11]


In [20]:
np_array_3 = np.arange(36)
print(np_array_3.shape)
np_array_4 = np_array_3.reshape(-1,1)
print(np_array_4.shape)

(36,)
(36, 1)
