In [12]:
import numpy as np
import pandas as pd

# np的核心api
np_array_1 = np.array([1,2,3,4])
print(np_array_1)
print('np_array_1.shape=' + str(np_array_1.shape)) 
print('np_array_1.ndim=' + str(np_array_1.ndim))

np_array_2 = np.array([[1,2,3,4],[2,3,4,5]])
print(np_array_2)
print('np_array_2.shape=' + str(np_array_2.shape)) 
print('np_array_2.ndim=' + str(np_array_2.ndim))

[1 2 3 4]
np_array_1.shape=(4,)
np_array_1.ndim=1
[[1 2 3 4]
 [2 3 4 5]]
np_array_2.shape=(2, 4)
np_array_2.ndim=2


In [21]:
# 创建空数组
np_empty_1 = np.empty([1,1,1],dtype=int)
print(np_empty_1)
print('np_empty_1.shape='+str(np_empty_1.shape))
print('np_empty_1.ndim='+str(np_empty_1.ndim))

[[[-1152921504606846976]]]
np_empty_1.shape=(1, 1, 1)
np_empty_1.ndim=3


In [25]:
# 创建为0的数组
np_zeros_1= np.zeros([1,1,1],dtype=int)
print(np_zeros_1)
print('np_zeros_1.shape='+str(np_zeros_1.shape))
print('np_zeros_1.ndim='+str(np_zeros_1.ndim))

[[[0]]]
np_zeros_1.shape=(1, 1, 1)
np_zeros_1.ndim=3


In [33]:
# 数组的常见操作
np_array_3 = np.arange(0,10)
print(np_array_3)
print('np_array_3.shape='+str(np_array_3.shape))
print('np_array_3.ndim='+str(np_array_3.ndim))


np_array_4 = np_array_3.reshape(5,2)
print(np_array_4)
print('np_array_4.shape='+str(np_array_4.shape))
print('np_array_4.ndim='+str(np_array_4.ndim))


np_array_5 = np_array_3.reshape(10,1)
print(np_array_5)
print('np_array_5.shape='+str(np_array_5.shape))
print('np_array_5.ndim='+str(np_array_5.ndim))


[0 1 2 3 4 5 6 7 8 9]
np_array_3.shape=(10,)
np_array_3.ndim=1
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
np_array_4.shape=(5, 2)
np_array_4.ndim=2
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
np_array_5.shape=(10, 1)
np_array_5.ndim=2
